name: CI/CD Pipeline for Farpa.ai

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: anishathalye/proof-html@v1
        with:
          directory: ./
          url_ignore:
            - "/teste.html"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'rff82-ai'
          directory: './'
          branch: 'main'
